---

- name: configs > Templates
  template:
    src:   "{{ item.template }}"
    dest:  "{{ manala_bind_configs_dir }}/{{ item.file }}"
    owner: root
    group: "{{ manala_bind_group }}"
    mode:  0644
  with_items: "{{ manala_bind_configs }}"
  notify:
    - bind reload
